#i need to decide which os i will be using (Linux)
#next i need to decide which version of java i need
#then we need to mention the command needed to run our java code

FROM 19-jdk-alpine3.16
COPY HelloWorld.class .
CMD java HelloWorld

